# Generated by Django 4.2.1 on 2023-06-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_image_alter_student_marklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Marklist',
            field=models.FileField(blank=True, null=True, upload_to='marklist/'),
        ),
    ]
